#! /bin/bash

kbd=$(echo $LANG | cut -c 4-5 | tr '[:upper:]' '[:lower:]')
#echo $kbd
while :
do
	isok=$(/usr/bin/setxkbmap -query | egrep ^layout | egrep -c "\ $kbd" )
	#echo $isok
	if [ "$isok" -ne "1" ]
	then
		#echo modif
		/usr/bin/setxkbmap -display :0 $kbd
	fi
	sleep 1
done
